### ISSUE TITLE
User update email event

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms2#153]
When we provide some way for the user to update there email we will need to generate an event

We can then have various lister update external system like the email forward database

**Comment by dpslwk** [comment]
HMS 1.0 does not allow change of email address

**Comment by geeksareforlife** [comment]
It does, doesn't it?  I know I can change mine.

I thought it was usernames you couldn't change, and if you had a username with an underscore you couldn't do anything?

**Comment by dpslwk** [comment]
hmm maybe I'm wrong then, will move back
