### ISSUE TITLE
Add Gulp to vagrant

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#16]
Gulp/Elixir is not currently installing as part of the vagrant image.  This fails to install due to the shared folder/symlink issue with vagrant.

It works inside the VM if the vagrant folder is copied to new directory and the installation happens in there.

Steps to install:

As root:

```
apt-get install curl
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get install -y nodejs
npm install --global gulp-cli
```

As vagrant user:

```
cd /path-to-files
npm install
```

**Comment by geeksareforlife** [comment]
I'm considering making the vagrant scripts do this copying (to /srv/vagrant) and installation, then writing a script to sit in the hms directory that will:

- copy all files in the resources directory in /vagrant to /srv/vagrant
- run gulp in /srv/vagrant
- copy all files in the public directory in /srv/vagrant to /vagrant

**Comment by dpslwk** [comment]
At this point maybe we should just skip it
Glup stuff can always be done outside the vagrant on the host, and that in the main laravel docs

'RepRap' Matt

**Comment by geeksareforlife** [comment]
Also need to copy the gulpfile

**Comment by geeksareforlife** [comment]
@dpslwk it can, but it's just a bit annoying - I don't really want node installed on my computer - the whole point of the vagrant is to have an easy to use dev environment.  I'll give it a quick go, as it's not like I can do anything else on this at the moment!
