### ISSUE TITLE
switch form mailtrap to mailhog

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms2#163]
So I'm playing around with build us a custom base box to help shorten vagrant up time and i've been using homestead and settler from larval as a starting point

One of the things that was added to homestead back in Feb is https://github.com/mailhog/MailHog

Mailhog is a catch all mail service much like mailtrap.io (which we use now)
but it runs inside the vagrant box and has a web front end that listens on :8085

Im very much in favour of switch to this for some of the following reasons

- no need to commit mail trap api key
- no need to share mailtrap login details
- email dev can be done offline as it all stays in the box

**Comment by geeksareforlife** [comment]
I'm fine with that
