### ISSUE TITLE
Application performance is terrible

### ISSUE THREAD

**Issue by roberthunt** [NottingHack/hms2#179]
Vagrant uses the "VirtualBox" type to mount shared folders by default which has terrible performance, this causes the application to be very sluggish when serving pages (typically 4-5s for a simple page). Ideally we want to switch to a better method such as "NFS" which has much better performance but may not be compatible with Windows hosts.

The vagrant documentation does mention that it should choose the best method for the environment:

> type (string) - The type of synced folder. If this is not specified, Vagrant will automatically choose the best synced folder option for your environment. Otherwise, you can specify a specific type such as "nfs". 

I'm not sure why it defaults to "VirtualBox" on OSX, if it could use "NFS" for OSX/Linux and fallback to "VirtualBox" that would probably be okay.

I think it needs some more investigation.

**Comment by geeksareforlife** [comment]
Is this since the new box? I don't remember if being this bad before

**Comment by dpslwk** [comment]
Nope its not the change in box

Matt

**Comment by roberthunt** [comment]
It's probably got worse as we've added more files to the project as it's file io that is slow in the shared folder.

**Comment by dpslwk** [comment]
Closing this until I can test on staging server, as its not that much of an issue for dev
