### ISSUE TITLE
user route from searching is a bit weird

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#241]
you get 

```
/users/1?user=1
```

The proper route (`/users/1`) works already

**Comment by dpslwk** [comment]
dashboard as mentioned in #240 would eventually change the search return path to something like

/home?user=1

Matt

**Comment by dpslwk** [comment]
hmm looked again at the code and this does need a fix

**Comment by dpslwk** [comment]
I can get rid of the param but not the ?
so end up with 
/users/1?
