### ISSUE TITLE
Note acceptor jam reconciliation 

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms2#242]
Sometimes the note acceptor jams or sticks at reading recording payment but not jammed. 
This can leave the `PENDING` entries in `transactions` and incomplete entries in `vend_log` 

> Daniel [12:54 PM] 
> hmm, ok. I've seen that a couple of times now. The problem seems to be the note acceptor swallows a note, but the arduino doesn't get/see the event to say it's happened. So it basically sits there forever waiting for a message that never arrives. but the resolution is to restart the note acceptor, then update the data in the same way as a jam (use sp_vend_success)
> 
> call sp_vend_success('<rfid serial>', <vend_tran_id>, 'CHANNELx', @err);
> to fix it. where channel1=£5, 2=£10
> get vend_tran_id from the vend table (it's _not_ transaction_id) (edited)

**Comment by roberthunt** [comment]
This may possibly be related to the a slow running query that was part of `sp_vend_success` which has now been fixed - essentially the server would take 30s+ to respond by which time the note acceptor would have given up waiting for the response. This functionality will probably be useful though.
