### ISSUE TITLE
Tool Statistics

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#245]
Build tool dashboards (similar to https://lspace.nottinghack.org.uk/stats/laser_usage.html, but maybe with graphs).

dashboards should be publically accessible and cover:

* number members inducted
* number inductors active/inactive
* number maintainers
* number of hours booked/month
* number of hours used/month
* totals of last two

**Comment by dpslwk** [comment]
closed in 34ee819e361503c990e319755ef868d9c1ea787c
