### ISSUE TITLE
Team Management

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms2#251]
Need to work out how we deal with adding and removing team roles to users, (this should be the preferred way rather than #250 )

* direct add for trustees? 
  * Trustees puts a person in a team
* request add for a user?
  * Member can request to join a team, Who approves? (trustees, existing team members)
* User opts to leave a team
  * notify team and trustees
* trustees direct removal

**Comment by geeksareforlife** [comment]
I think that being able to add people to a team role should be a seperate permission.  That way you can give it to the trustee role, but also give it out as needed.

Some teams would make sense to allow 1 or 2 of the existing team members to allow new team members, but for others it might not make much sense.

**Comment by dpslwk** [comment]
Hmm interesting idea

`role.team.add.all`
`role.team.remove.all`
`role.team.approveRemoval.all`
`role.team.add.membership`
`role.team.remove.membership`
`role.team.approveRemoval.membership`
`role.team.add.metalworking`
`role.team.remove.metalworking`
`role.team.approveRemoval.metalworking`

Something like that?
Would need to generate these on the fly when creating new teams



Matt

**Comment by geeksareforlife** [comment]
I was more thinking of just having a general:

`role.team.add`

etc, and making a role called something like `team administrators`, but I actually like your idea better

**Comment by dpslwk** [comment]
Mind we don’t assigned permissions to users, so to limit adding or approval to just some members of a team would be a pain


Matt

**Comment by geeksareforlife** [comment]
It would be manual, absolutely.  That might be a good idea...

**Comment by dpslwk** [comment]
closed via #400
