### ISSUE TITLE
Pagination within Bootstrap and Laravel

### ISSUE THREAD

**Issue by jlacy23** [NottingHack/hms2#267]
Pagination within Bootstrap has particular classes that need to be used in order for it to be shown correctly. Any ideas on how to get it working?

**Comment by geeksareforlife** [comment]
Do you mean get the laravel blade templates to pump out the correct bootstrap code?

Are you working on the new bootstrap 4 branch with @mathw ?

**Comment by jlacy23** [comment]
Yes believe so 

And 

Yes

**Comment by jlacy23** [comment]
Fixed - Files Found
