### ISSUE TITLE
Bootstrap Version

### ISSUE THREAD

**Issue by jlacy23** [NottingHack/hms2#268]
On Projects panel the Project complete button goes nowhere. Is this a problem with my copy? Here 

      @can('project.edit.self')
        @if ($project->getState() == \HMS\Entities\Members\Project::PROJCET_ACTIVE)
          @if ($project->getUser() == \Auth::user())
          <a href="javascript:void(0);" onclick="$(this).find('form').submit();" class="btn btn-primary btn-sm">
            <form action="{{ route('projects.markComplete', $project->getId()) }}" method="POST" style="display: none">
              {{ method_field('PATCH') }}
              {{ csrf_field() }}
            </form>
            <i class="fa fa-check" aria-hidden="true"></i> Mark Complete
          </a>
          @else
          <a href="javascript:void(0);" onclick="$(this).find('form').submit();" class="btn btn-primary btn-sm btn-sm-spacing">
            <form action="{{ route('projects.markAbandoned', $project->getId()) }}" method="POST" style="display: none">
              {{ method_field('PATCH') }}
              {{ csrf_field() }}
            </form>
            <i class="fa fa-frown-o" aria-hidden="true"></i> Mark Abandoned
          </a><br />
          @endif
        @endif
        @if ($project->getState() != \HMS\Entities\Members\Project::PROJCET_ACTIVE)
        <a href="javascript:void(0);" onclick="$(this).find('form').submit();">
          <form action="{{ route('projects.markActive', $project->getId()) }}" method="POST" style="display: none">
            {{ method_field('PATCH') }}
            {{ csrf_field() }}
          </form>
          <i class="fa fa-play" aria-hidden="true"></i> Resume Project
        </a>
        @endif
      @endcan
```
https://hmsdev/projects File hms2\resources\views\members\project\index.blade.php

**Comment by dpslwk** [comment]
its all valid code and works, nothing to fix
form inside the a ref and the js call in the href allow it to be a PATCH request not a GET
