### ISSUE TITLE
Should we use HMS or HMS2?

### ISSUE THREAD

**Issue by kasbah** [NottingHack/hms2#277]
Hey, I am part of Bristol Hackspace and we are considering using HMS/HMS2. Which would you recommend, have you migrated to HMS2 yourself?

**Comment by jlacy23** [comment]
In my opinion, HMS2 has it's benefits that waiting will make it a much better for everyone, I am currently working on the UI and HMS2 will be mobile ready from the ground up. HMS while is able to be used on a mobile device, isn't the best experience. The only problem is I cannot be the one to give a timeline however i'm sure one of the other guys in the team might give you a ballpark date.

**Comment by geeksareforlife** [comment]
Hi @kabash

Realisitically, we are probably a couple of months at least away from an initial release of HMS2.  That said, I completely agree with @jlacy23 that HMS2 is a better user experience.

Whichever you choose, you will need to do a fair amount of work - both systems are quite tightly integrated into our systems in the space.

If you are still interested, we'd be happy to advise on how to go about this!  It would probably be best to fork the project off into your own org, and work from there to start with.

**Comment by kasbah** [comment]
Ok, thanks! I guess we'll evaluate both in that case. I'll ping you if we have any trouble (which is probably inevitable).
