### ISSUE TITLE
Need to be able to access snackspace from found user as an admin

### ISSUE THREAD

**Issue by ocatelle** [NottingHack/hms2#286]

**Comment by dpslwk** [comment]
a lot of things related to accessing found user stuff is yet to be implemented and will be handled via the #161 landing page/user dashboard, which will act replace the /user destination of searchs

**Comment by ocatelle** [comment]
This is a snackspace version of #240 which James requested I create and assign.

**Comment by jadams23** [comment]
sorted in #311

**Comment by dpslwk** [comment]
should be fixed with #370
