### ISSUE TITLE
Add profile model and seeder - linked to Users

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#29]
Need a mix of profile data.  For example, in some of the young members, their 18th birthday should be tomorrow.

**Comment by cooperaj** [comment]
Will get this in as soon as the yaml change #24 gets figured out since it'll affect this

**Comment by geeksareforlife** [comment]
The last PR added the profile model, but we still need a profile seeder.

Also, I think we should add date of birth to the profile - should be allowed to be NULL, except in young members (obviously this last bit is not in this issue)

**Comment by geeksareforlife** [comment]
completed in #105
