### ISSUE TITLE
Add blameable doctrine plugin

### ISSUE THREAD

**Issue by Hodgy** [NottingHack/hms2#34]
http://www.laraveldoctrine.org/docs/1.2/extensions/blameable 

Allows automatic tracking of who has made changes

**Comment by geeksareforlife** [comment]
@Hodgy you still happy to work on this one?

**Comment by Hodgy** [comment]
Yeah. Ill take a look when i have time

**Comment by geeksareforlife** [comment]
@Hodgy do we think that this will make it in?  I know you were having issues with getting it to work

**Comment by dpslwk** [comment]
Do we need it?

Matt
