### ISSUE TITLE
Snackspace permissions for purchase/payment

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms2#359]
'snackspace.purchase', // Can buy stuff either vend or chargeable tool
'snackspace.purchase.creditOnly', // Can buy stuff either vend or chargeable tool but only if there in credit (ex members)
'snackspace.payment', // can make a payment 
'snackspace.payment.debtOnly', // can make a payment but only if there in debt (ex members)

to be used by nh-vend and nt-tool

**Comment by daniel1111** [comment]
note that even with creditOnly, nh-tool is realistically going to have to let members go into debt with the laser, as it will never cut off power if the member goes into debt mid-use (the same way it lets you go over the credit limit)

**Comment by dpslwk** [comment]
Yeah but then they would not have the tools.use permission its kinda a mute check I guess


Matt

**Comment by dpslwk** [comment]
some sudo code around how I think this all needs to work 

allow tool sign on perm checks

`if not during a maintenance slot`
`tools.use && tools.<toolperm>.use && (snackspace.purchase || snackspace.purchase.creditOnly)`

```
if user can (tools.use && tools.<toolperm>.use) {
    if user can snackspace.purchase && is not over credit limit {
        allow
    } else if user can snackspace.purchase.creditOnly && is in credit {
        allow
    } else {
        deny
    }
} else {
    deny   
}
```

`if during maintenance` // if trustees agreed not to charge we drop the snackspace perms here
`tools.use && tools.<toolperm>.maintain && (snackspace.purchase || snackspace.purchase.creditOnly)`

allow vend check (VEND)
`(snackspace.purchase && not over credit) || (snackspace.purchase.creditOnly && in credit)`

allow payment (NOTE)
`snackspace.payment || (snackspace.payment.debtOnly && in debt)`

**Comment by dpslwk** [comment]
ok new sudo code for tool perms
```
if (user can not 'tool.use') {
    // basically not a current or young member
    deny
} 

if (tool is 'disabled' || during a 'maintenance' slot) {
    // we need maintain perm
    if ( user can (tools.<toolperm>.maintain)) {
        // note we wont charge a maintainer for this allow
        allow_free
    } else {
        deny
    }
}

if (tool 'restricted') {
    if (user can 'tools.<toolperm>.use') {
        if (user can 'snackspace.purchase' && is not over credit limit) {
            allow
        } else if (user can 'snackspace.purchase.creditOnly' && is in credit) {
            allow
        } else {
            deny
        }
    } else {
        deny   
    }
} else {
    // tool is not restricted
    allow
}
```

**Comment by dpslwk** [comment]
inductors will have the 'tools._TOOL_PERMISSION_NAME_.induct' permission

**Comment by daniel1111** [comment]
How would we disable access for a specific member to a normally unrestricted tool?

see https://github.com/NottingHack/instrumentation/issues/6

**Comment by dpslwk** [comment]
Hmm well that was originally about banning a member from an induction tool

We’d maybe have to add a tool.<toolperm>.banned role with a matching tool.<toolperm>.useDisallowed permission??

Matt

**Comment by daniel1111** [comment]
I guess we might have to do something like that. Although if we've never actually needed it...
