### ISSUE TITLE
Add meta table and retrieving functions

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#41]
The meta table holds all variable information, such as wifi and access codes and settings for the system.

**Comment by geeksareforlife** [comment]
We currently use a DB table for this (in HMS 1.0).  Should we move to something like Redis for 2.0?

**Comment by dpslwk** [comment]
IIRC redis would still need a DB table as a permanent store to keep things between reboot of the redis server

Matt

**Comment by geeksareforlife** [comment]
It may have done in the past, but uses single-file persistance nowadays http://redis.io/topics/persistence

**Comment by roberthunt** [comment]
I wouldn't overcomplicate it with another dependency at this point, Redis is nice but not something we should start using for the sake of a config table.

Things like Redis (in-memory data stores) start to become more useful when you're running multiple instances of the application and need to share things like session data between instances. They are also useful for distributed caching of data.

**Comment by geeksareforlife** [comment]
ok doke

**Comment by cooperaj** [comment]
Yeah. Overkill for a settings table.
