### ISSUE TITLE
Cannot update new tool booking lengths

### ISSUE THREAD

**Issue by Samathy** [NottingHack/hms2#452]
When creating a new tool, the booking lengths ( minimum and maximum ) default to `1` and cannot be updated.

Attempting to update the booking lengths doesnt do anything.

Attempted in Firefox 73 and Chromium 80 on HMS 2.4.8 ( Version in prod at Nottinghack ).

**Comment by dpslwk** [comment]
fixed in 02b1b8be8c06a81af3b7122509324afc2749bcc5
