### ISSUE TITLE
New tools default to DISABLED status and cannot be updated.

### ISSUE THREAD

**Issue by Samathy** [NottingHack/hms2#453]
After creating a new tool, it defaults to a DISABLED state.
There is no clear way to update the tool to mark it as in-use. Even if the active user is an inductor, maintainer or member of the Trustee's group.

**Comment by dpslwk** [comment]
Only network team should be creating tools (trustees should have never had access to that button)
since part of creating a tool is setting up the RFID controller and a tool can not move from DISABLED to available until this set is done
there is no way to to this in HMS at all, is a manual DB edit

**Comment by Samathy** [comment]
While I can now understand why the default is `DISABLED`, requiring a manual DB edit for _anything_ is not good.

Including the ability to set the status of a tool should probably be within the tool's edit page, even if only network team have the rights to see and push it.
