### ISSUE TITLE
Allow Trustees to book tool slots marked 'Trustee Booking' (Feature Request)

### ISSUE THREAD

**Issue by Samathy** [NottingHack/hms2#454]
In a similar fashion to how maintainers can book maintenance slots on a tool, people in the Trustee HMS group should be able to book `Trustees Booking` slots for unlimited amounts of hours on a tool.

This only really makes sense for the Classroom _tool_.

**Comment by dpslwk** [comment]
the classroom is not a tool its a bookable room, which needs wholly different code writing around its use cases since they are so different to how a tool is use and managed,
and since `trustee` booking is not a concept that works for a tool it won't be added
