### ISSUE TITLE
Button To Ban Member

### ISSUE THREAD

**Issue by themrflibble** [NottingHack/hms2#474]
On Tuesday 2020-11-03, the Board had a chat about the issue of not being able to ban people on HMS at the moment.
The Trustees decided that although an N-1 protection around the ban mechanism in HMS would be desirable, we really need the ability to ban members soon.

We'd really like there to just be a button that any of the board can press to ban a given member. When a member is banned, there **_must_** be a notification of that action sent to trustees@. But, any board member should be able to action a ban, or un-ban.

**Comment by dpslwk** [comment]
closed via 3f6ad347609c3fcc9d73bd2e96af086ef206f410

notifications added but should still look at multiple confirmation in the future
