### ISSUE TITLE
Calendar Event Over Midnight And Start In Past Error

### ISSUE THREAD

**Issue by themrflibble** [NottingHack/hms2#479]
A member requested entry for a few mins in the future (by the time I got to it, it was the past), and their end date spanned past midnight.

**Issue 1**
I cannot reduce their 2215 slot to anything less than 0015 the next day

**Issue 2**
I cannot delete their slot

**Comment by dpslwk** [comment]
1) use week view, extend all the way to the end of the same day so that the calendar scrolls then drag to the previous day

2) once a slot has started it can not be removed this is by design

**Comment by themrflibble** [comment]
Not intuitive, but, it's a fringe case. And I now know.
