### ISSUE TITLE
EU Cookie law

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/hms2#49]
We never fixed this in hms1 but i think this be done in 2.x and given this nice laravel plug-in i expect it to be quite quick and easy to get up and running then the front end boys can just style it out

https://github.com/spatie/laravel-cookie-consent

**Comment by dpslwk** [comment]
ok i've installed the plugin in with fd17901363c00b37a9db75fb72241d14c2a34d9c
just needs some styling from @mathw

**Comment by geeksareforlife** [comment]
From their site, this is "Postcardware" -  we should send them a postcard if we use this in production :)

"You're free to use this package (it's MIT-licensed), but if it makes it to your production environment you are required to send us a postcard from your hometown, mentioning which of our package(s) you are using.

Our address is: Spatie, Samberstraat 69D, 2060 Antwerp, Belgium.

The best postcards will get published on the open source page on our website."

**Comment by cooperaj** [comment]
I get it's a silly thing. But using 'required' as a part of the language is in direct contravention of the MIT license.

**Comment by geeksareforlife** [comment]
very true!  I still think we should send them one though :)
