### ISSUE TITLE
Tool bookings

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#52]
Creating an issue to store some info

https://murze.be/2016/05/how-to-setup-and-use-the-google-calendar-api/
https://murze.be/2016/05/package-manage-events-google-calendar/

**Comment by roberthunt** [comment]
Also this:
https://laracasts.com/discuss/channels/tips/google-api-service-account-connection-laravel-5

For reference, HMS 1.0 used the wrong type of account which required the manual "auth loop" - these links show how to use a service account with a key file which is a better solution.

**Comment by geeksareforlife** [comment]
Yep, the service account didn't exist when I implemented 1.0 - it was introduced a few months later and I always meant to move to that!

**Comment by dpslwk** [comment]
Maintance bookings should not be time limited

**Comment by geeksareforlife** [comment]
https://github.com/spatie/laravel-google-calendar
