### ISSUE TITLE
Members of the trustee team cannot remove Users, Inductors or Maintainers despite having the correct permission strings to do so

### ISSUE THREAD

**Issue by DauntlessAq** [NottingHack/hms2#553]
The trustee team has the following permission strings, which should allow both adding and removing users, inductors and maintainers from tools:
https://github.com/NottingHack/hms2/blob/main/config/roles.php#L94-L96
https://github.com/NottingHack/hms2/blob/main/config/roles.php#L403-L405

There is no issue with adding users, inductors and maintainers.

However, while the remove button is present, pressing it redirects to https://hms.nottinghack.org.uk/home, with banner stating 'unauthorised'

![image](https://user-images.githubusercontent.com/117931742/201151163-49b18429-b9db-489e-a9b6-dcf6d3bc1942.png)

![image](https://user-images.githubusercontent.com/117931742/201151296-183381c0-1f6b-494f-bae2-9e4d65d8338a.png)

It therefore seems that these permission strings are not functioning correctly.

**Comment by mooped** [comment]
Further to this it seems like users who are inductors for a tool cannot appoint users, though they are able to appoint other inductors or maintainers. This prevents members of Teams from keeping track of inducted users for tools that don't yet have RFID.
This issue was confirmed by Bob Wood.
